version: '3.8'

services:
  mongodb:
    image: mongo:3.6.20
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.dls
